# Generated by Django 2.0.7 on 2018-07-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external_page', '0042_auto_20180721_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128, null=True)),
                ('datetime', models.DateTimeField()),
                ('city', models.CharField(max_length=64, null=True)),
                ('city_district', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('location_name', models.CharField(max_length=64, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_page.Instructor')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_page.Hobby')),
            ],
        ),
        migrations.CreateModel(
            name='HobbyEventSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('hobby_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby_event.HobbyEvent')),
            ],
        ),
    ]
