# Generated by Django 2.0.7 on 2018-07-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyevent',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
