# Generated by Django 2.0.7 on 2018-07-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0002_auto_20180721_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyevent',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
