# Generated by Django 2.0.7 on 2018-07-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0003_auto_20180721_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyevent',
            name='location_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
