# Generated by Django 2.0.7 on 2018-07-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0004_auto_20180721_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyevent',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hobbyevent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
