# Generated by Django 2.0.7 on 2018-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0005_auto_20180721_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyevent',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
