# Generated by Django 2.0.7 on 2018-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0006_hobbyevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyevent',
            name='event_color_blue',
            field=models.PositiveIntegerField(default=255),
        ),
        migrations.AddField(
            model_name='hobbyevent',
            name='event_color_green',
            field=models.PositiveIntegerField(default=255),
        ),
        migrations.AddField(
            model_name='hobbyevent',
            name='event_color_red',
            field=models.PositiveIntegerField(default=255),
        ),
    ]
