# Generated by Django 2.0.7 on 2018-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0008_hobbyevent_datetime_for_rsvp_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbyevent',
            name='datetime_for_rsvp_close',
        ),
        migrations.AddField(
            model_name='hobbyevent',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
