# Generated by Django 2.0.7 on 2018-07-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0009_auto_20180721_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyevent',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
