# Generated by Django 2.0.7 on 2018-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0011_hobbyevent_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyevent',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
