# Generated by Django 2.0.7 on 2018-07-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0012_hobbyevent_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyeventsignup',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hobbyeventsignup',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
