# Generated by Django 2.0.7 on 2018-07-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0013_auto_20180725_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyeventsignup',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hobbyeventsignup',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hobbyeventsignup',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hobbyeventsignup',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
