# Generated by Django 2.0.7 on 2018-07-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_event', '0020_auto_20180729_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbyeventsignup',
            name='user',
        ),
    ]
