# Generated by Django 2.0.7 on 2018-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='maximum_students',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_in_student_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_in_teacher_home',
            field=models.BooleanField(default=True),
        ),
    ]
