# Generated by Django 2.0.7 on 2018-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0002_auto_20180711_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=256, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('work_in_student_home', models.BooleanField(default=False)),
                ('work_in_instructor_home', models.BooleanField(default=True)),
                ('maximum_students', models.PositiveIntegerField(default=2)),
                ('hobbies', models.ManyToManyField(to='external_page.Hobby')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
