# Generated by Django 2.0.7 on 2018-07-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0004_instructor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='city',
            field=models.CharField(default='Stockholm', max_length=128),
        ),
        migrations.AddField(
            model_name='instructor',
            name='zip_code',
            field=models.CharField(default='19141', max_length=10),
        ),
    ]
