# Generated by Django 2.0.7 on 2018-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0007_auto_20180712_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='city',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='hobbies',
            field=models.ManyToManyField(default=None, to='external_page.Hobby'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
