# Generated by Django 2.0.7 on 2018-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0008_auto_20180712_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='hobbies',
            field=models.ManyToManyField(null=True, to='external_page.Hobby'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
