# Generated by Django 2.0.7 on 2018-07-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0011_auto_20180712_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='hobbies',
            field=models.ManyToManyField(to='external_page.Hobby'),
        ),
    ]
