# Generated by Django 2.0.7 on 2018-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0013_auto_20180713_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.CharField(blank=True, choices=[('N', 'No answer'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N', max_length=1, null=True),
        ),
    ]
