# Generated by Django 2.0.7 on 2018-07-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0014_auto_20180713_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
