# Generated by Django 2.0.7 on 2018-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0017_auto_20180714_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='price',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(default='1.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='maximum_students',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
