# Generated by Django 2.0.7 on 2018-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0018_auto_20180716_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='price_model',
            field=models.CharField(blank=True, choices=[('H', 'Per timme'), ('T', 'Per tillfälle')], default='H', max_length=1, null=True),
        ),
    ]
