# Generated by Django 2.0.7 on 2018-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0019_instructor_price_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='price_model',
            field=models.CharField(choices=[('H', 'Per timme'), ('T', 'Per tillfälle')], default='H', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
    ]
