# Generated by Django 2.0.7 on 2018-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0020_auto_20180716_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
