# Generated by Django 2.0.7 on 2018-07-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0021_auto_20180716_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='instructor',
            name='hobbies',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='external_page.Hobby'),
        ),
    ]
