# Generated by Django 2.0.7 on 2018-07-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0023_auto_20180716_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
