# Generated by Django 2.0.7 on 2018-07-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0024_instructor_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='is_active',
            new_name='valid_profile',
        ),
    ]
