# Generated by Django 2.0.7 on 2018-07-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0025_auto_20180716_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='city_district',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
