# Generated by Django 2.0.7 on 2018-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0028_auto_20180718_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='price_model',
            field=models.CharField(choices=[('H', 'per timme'), ('X', 'per timme och per person'), ('T', 'per tillfälle'), ('Y', 'per tillfälle och per person')], default='H', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
