# Generated by Django 2.0.7 on 2018-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0029_auto_20180719_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
