# Generated by Django 2.0.7 on 2018-07-19 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_page', '0031_auto_20180719_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('message', models.CharField(max_length=2048, null=True)),
                ('message_sent', models.BooleanField(default=False)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
