# Generated by Django 2.0.7 on 2018-07-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0034_auto_20180719_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructormessage',
            name='first_name',
        ),
    ]
