# Generated by Django 2.0.7 on 2018-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0035_remove_instructormessage_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormessage',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
