# Generated by Django 2.0.7 on 2018-07-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0036_instructormessage_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormessage',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
