# Generated by Django 2.0.7 on 2018-07-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0037_auto_20180719_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormessage',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
