# Generated by Django 2.0.7 on 2018-07-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0038_auto_20180719_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormessage',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
