# Generated by Django 2.0.7 on 2018-07-20 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0039_auto_20180719_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormessage',
            name='time_now',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
