# Generated by Django 2.0.7 on 2018-07-20 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_page', '0040_instructormessage_time_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True, unique=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('city_district', models.CharField(max_length=64, null=True)),
                ('zip_code', models.CharField(max_length=6, null=True)),
                ('gender', models.CharField(blank=True, choices=[('N', 'No answer'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N', max_length=1, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128, null=True)),
                ('datetime', models.DateTimeField()),
                ('city', models.CharField(max_length=64, null=True)),
                ('city_district', models.CharField(max_length=64, null=True)),
                ('adress', models.CharField(max_length=64, null=True)),
                ('location_name', models.CharField(max_length=64, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_page.Instructor')),
            ],
        ),
        migrations.AlterField(
            model_name='instructormessage',
            name='message',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
