# Generated by Django 2.0.7 on 2018-07-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0041_auto_20180720_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_host',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
