# Generated by Django 2.0.7 on 2018-07-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0042_auto_20180721_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='instructormessage',
            name='message',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
