# Generated by Django 2.0.7 on 2018-07-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0044_auto_20180725_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_private_instructor',
            field=models.BooleanField(default=True),
        ),
    ]
