# Generated by Django 2.0.7 on 2018-07-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0050_instructor_accepted_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city_district',
        ),
        migrations.AddField(
            model_name='customer',
            name='accepted_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='valid_profile',
            field=models.BooleanField(default=False),
        ),
    ]
