# Generated by Django 2.0.7 on 2018-07-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0051_auto_20180728_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
