# Generated by Django 2.0.7 on 2018-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_page', '0052_instructor_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormessage',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instructormessage',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instructormessage',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
